name: MongoDB Environment Variable Testing
on:
  push:
    branches:
      - main
      - dev

env:
  MONGODB_DB_NAME: testing_db

jobs:
  test:
    env:
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code:
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Print MongoDB Env Variable
        run: |
          echo "MONGODB_DB_NAME is $MONGODB_DB_NAME"
          echo "MONGODB_USERNAME is $MONGODB_USERNAME"
          echo "MONGODB_PASSWORD is $MONGODB_PASSWORD"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "MONGODB_DB_NAME is $MONGODB_DB_NAME"
          echo "MONGODB_USERNAME is $MONGODB_USERNAME"
          echo "MONGODB_PASSWORD is $MONGODB_PASSWORD"

